version: '3'

services:

 mongo:
   image: mongo:latest
   container_name: mongo
   ports:
     - "27017:27017"  

 server:
   build: ./server
   expose:
     - ${APP_SERVER_PORT}
   environment:
     API_HOST: ${API_HOST}
     API_SERVER_PORT: ${APP_SERVER_PORT}
   ports:
     - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
   volumes:
     - ./server/app.js:/srv/app/server/app.js
     - ./server/handlers:/srv/app/server/handlers
     - ./server/models:/srv/app/server/models
     - ./server/routes:/srv/app/server/routes
   command: npm start
   depends_on:
     - mongo  

 client:
   build: ./client
   expose:
     - ${REACT_APP_PORT}
   environment:
     - REACT_APP_PORT = ${REACT_APP_PORT}
   ports:
     - ${REACT_APP_PORT}:${REACT_APP_PORT}
   volumes:
     - ./client/client/public:/srv/app/client/client/public
     - ./client/client/src:/srv/app/client/client/src
     - ./client/handlers:/srv/app/client/handlers
     - ./client/models:/srv/app/client/models
     - ./client/routes:/srv/app/client/routes
   links:
     - server  
   command: npm start  



